const fs = require('fs');
const path = require('path');

const dirs = [
  'backend/src/config',
  'backend/src/routes',
  'backend/src/controllers',
  'backend/src/services',
  'backend/src/repositories',
  'backend/src/models',
  'backend/src/schemas',
  'backend/src/middleware',
  'backend/src/types',
  'backend/src/utils',
  'backend/src/constants',
  'backend/src/docs',
  'backend/tests/unit',
  'backend/tests/integration',
  'backend/tests/fixtures',
  'backend/scripts',
  'backend/docs'
];

const files = [
  'backend/src/app.ts',
  'backend/src/server.ts',
  'backend/src/config/env.ts',
  'backend/src/config/database.ts',
  'backend/src/config/cors.ts',
  'backend/src/config/security.ts',
  'backend/src/config/logger.ts',
  'backend/src/routes/index.ts',
  'backend/src/routes/auth.routes.ts',
  'backend/src/routes/delivery.routes.ts',
  'backend/src/routes/partner.routes.ts',
  'backend/src/routes/assignment.routes.ts',
  'backend/src/routes/order.routes.ts',
  'backend/src/routes/audit.routes.ts',
  'backend/src/routes/report.routes.ts',
  'backend/src/routes/health.routes.ts',
  'backend/src/controllers/auth.controller.ts',
  'backend/src/controllers/delivery.controller.ts',
  'backend/src/controllers/partner.controller.ts',
  'backend/src/controllers/assignment.controller.ts',
  'backend/src/controllers/order.controller.ts',
  'backend/src/controllers/audit.controller.ts',
  'backend/src/controllers/report.controller.ts',
  'backend/src/services/auth.service.ts',
  'backend/src/services/delivery.service.ts',
  'backend/src/services/partner.service.ts',
  'backend/src/services/assignment.service.ts',
  'backend/src/services/order.service.ts',
  'backend/src/services/audit.service.ts',
  'backend/src/services/report.service.ts',
  'backend/src/repositories/auth.repository.ts',
  'backend/src/repositories/delivery.repository.ts',
  'backend/src/repositories/partner.repository.ts',
  'backend/src/repositories/assignment.repository.ts',
  'backend/src/repositories/order.repository.ts',
  'backend/src/repositories/audit.repository.ts',
  'backend/src/repositories/report.repository.ts',
  'backend/src/models/User.model.ts',
  'backend/src/models/Delivery.model.ts',
  'backend/src/models/DeliveryPartner.model.ts',
  'backend/src/models/Assignment.model.ts',
  'backend/src/models/Order.model.ts',
  'backend/src/models/AuditLog.model.ts',
  'backend/src/models/TimelineEvent.model.ts',
  'backend/src/schemas/auth.schema.ts',
  'backend/src/schemas/delivery.schema.ts',
  'backend/src/schemas/partner.schema.ts',
  'backend/src/schemas/assignment.schema.ts',
  'backend/src/schemas/order.schema.ts',
  'backend/src/schemas/audit.schema.ts',
  'backend/src/schemas/report.schema.ts',
  'backend/src/middleware/auth.middleware.ts',
  'backend/src/middleware/role.middleware.ts',
  'backend/src/middleware/permission.middleware.ts',
  'backend/src/middleware/validation.middleware.ts',
  'backend/src/middleware/error.middleware.ts',
  'backend/src/middleware/notFound.middleware.ts',
  'backend/src/middleware/rateLimit.middleware.ts',
  'backend/src/middleware/requestId.middleware.ts',
  'backend/src/types/auth.types.ts',
  'backend/src/types/delivery.types.ts',
  'backend/src/types/partner.types.ts',
  'backend/src/types/assignment.types.ts',
  'backend/src/types/order.types.ts',
  'backend/src/types/audit.types.ts',
  'backend/src/types/report.types.ts',
  'backend/src/types/common.types.ts',
  'backend/src/utils/jwt.ts',
  'backend/src/utils/password.ts',
  'backend/src/utils/pagination.ts',
  'backend/src/utils/response.ts',
  'backend/src/utils/asyncHandler.ts',
  'backend/src/utils/errors.ts',
  'backend/src/constants/roles.ts',
  'backend/src/constants/permissions.ts',
  'backend/src/constants/deliveryStatus.ts',
  'backend/src/constants/partnerStatus.ts',
  'backend/src/constants/assignmentStatus.ts',
  'backend/src/docs/openapi.ts',
  'backend/scripts/README.md',
  'backend/docs/API-CONTRACT.md',
  'backend/docs/ARCHITECTURE.md',
  'backend/docs/DATABASE.md',
  'backend/.env.example',
  'backend/.gitignore',
  'backend/package.json',
  'backend/tsconfig.json',
  'backend/README.md'
];

dirs.forEach(dir => {
  fs.mkdirSync(path.join(__dirname, dir), { recursive: true });
});

files.forEach(file => {
  fs.writeFileSync(path.join(__dirname, file), '');
});

console.log('Scaffolding complete.');
