import { Permission, Role } from '@/types/auth';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: [
    'DELIVERY_VIEW', 'DELIVERY_ASSIGN', 'DELIVERY_REASSIGN', 'DELIVERY_STATUS_UPDATE', 
    'DELIVERY_COMPLETE', 'DELIVERY_FAIL', 'PARTNER_VIEW', 'PARTNER_CREATE', 'PARTNER_EDIT', 
    'PARTNER_STATUS_UPDATE', 'REPORT_VIEW', 'REPORT_EXPORT', 'AUDIT_VIEW', 'TIMELINE_VIEW'
  ],
  ADMIN: [
    'DELIVERY_VIEW', 'DELIVERY_ASSIGN', 'DELIVERY_REASSIGN', 'DELIVERY_STATUS_UPDATE', 
    'DELIVERY_COMPLETE', 'DELIVERY_FAIL', 'PARTNER_VIEW', 'PARTNER_CREATE', 'PARTNER_EDIT', 
    'PARTNER_STATUS_UPDATE', 'REPORT_VIEW', 'REPORT_EXPORT', 'AUDIT_VIEW', 'TIMELINE_VIEW'
  ],
  DELIVERY_MANAGER: [
    'DELIVERY_VIEW', 'DELIVERY_ASSIGN', 'DELIVERY_REASSIGN', 'DELIVERY_STATUS_UPDATE', 
    'DELIVERY_COMPLETE', 'DELIVERY_FAIL', 'PARTNER_VIEW', 'PARTNER_CREATE', 'PARTNER_EDIT', 
    'PARTNER_STATUS_UPDATE', 'REPORT_VIEW', 'AUDIT_VIEW', 'TIMELINE_VIEW'
  ],
  OPERATIONS_MANAGER: [
    'DELIVERY_VIEW', 'DELIVERY_STATUS_UPDATE', 'PARTNER_VIEW', 'TIMELINE_VIEW'
  ],
  ORDER_MANAGER: [
    'DELIVERY_VIEW', 'TIMELINE_VIEW' // Could have assignment if configured
  ],
  CATALOG_MANAGER: [
    // No delivery access
  ],
  CUSTOMER_SUPPORT: [
    'DELIVERY_VIEW', 'TIMELINE_VIEW'
  ],
  REPORTS_MANAGER: [
    'REPORT_VIEW', 'REPORT_EXPORT'
  ]
};
