export const PERMISSIONS = {
  DELIVERY_VIEW: 'DELIVERY_VIEW',
  DELIVERY_ASSIGN: 'DELIVERY_ASSIGN',
  DELIVERY_REASSIGN: 'DELIVERY_REASSIGN',
  DELIVERY_STATUS_UPDATE: 'DELIVERY_STATUS_UPDATE',
  DELIVERY_COMPLETE: 'DELIVERY_COMPLETE',
  DELIVERY_FAIL: 'DELIVERY_FAIL',
  PARTNER_VIEW: 'PARTNER_VIEW',
  PARTNER_CREATE: 'PARTNER_CREATE',
  PARTNER_EDIT: 'PARTNER_EDIT',
  PARTNER_STATUS_UPDATE: 'PARTNER_STATUS_UPDATE',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  AUDIT_VIEW: 'AUDIT_VIEW',
  TIMELINE_VIEW: 'TIMELINE_VIEW'
} as const;

export type Permission = keyof typeof PERMISSIONS;
