export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OUTLET_MANAGER: 'OUTLET_MANAGER',
  KITCHEN_MANAGER: 'KITCHEN_MANAGER',
  DELIVERY_MANAGER: 'DELIVERY_MANAGER',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  MARKETING_MANAGER: 'MARKETING_MANAGER'
} as const;

export type Role = keyof typeof ROLES;
